TILEWIDTH = 7
TILEHEIGHT = 7

NROWS = 100
NCOLS = 100

SCREENWIDTH = NCOLS*TILEWIDTH
SCREENHEIGHT = NROWS*TILEHEIGHT
SCREENSIZE = (SCREENWIDTH, SCREENHEIGHT)

BLACK = (0, 0, 0)
WHITE = (255, 255, 255)